jobs:
  include:
    - stage: building
      name: pc
      os: windows
      language: node_js
      node_js: "10"
      env:
        - YARN_GPG=no

    - name: mac
      os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"

    - stage: deploy
      name: deploy to github
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: "Soundboard-mac.zip"
        skip_cleanup: true
        on:
          tags: true

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      yarn package-win && powershell Compress-Archive -Path release-builds/pc -DestinationPath Soundboard-pc
    else
      yarn package-mac &&  zip -r Soundboard-mac.zip release-builds/mac
    fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"